#!/bin/sh

# This script does the following:
#  when called from sxiv key handler, finds image directory.
# If directory is environment variable WPDIR{1..2}, sets wallpaper
# on corresponding monitor

# Location of link to wallpaper link.
#
# Why I even did this, I have tiling wm. I never see the wallpaper  ¯\_(ツ)_/¯
file=$1
fullpath="$(realpath $file)"
dir="$(dirname ${fullpath})/"

case $dir in
		$WPDIR1)
		bgloc="${XDG_DATA_HOME:-$HOME/.local/share/}/bg"
		;;
$WPDIR2)
		bgloc="${XDG_DATA_HOME:-$HOME/.local/share/}/bg2"
		;;
*)
		notify-send "file not in designated wallpaper directory"
		file=""
		;;
esac

[ -f "$file" ] && ln -sf "$(readlink -f "$file")" "$bgloc" && notify-send -i "$bgloc" "Changing wallpaper..."

[ -d "$1" ] && ln -sf "$(find "$(readlink -f "$1")" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1)" "$bgloc" && notify-send -i "$bgloc" "Random Wallpaper chosen."

# If pywal is installed, use it.
#wal -i "$(readlink -f "$bgloc")" -o "${XDG_CONFIG_HOME:-$HOME/.config}/wal/postrun" >/dev/null 2>&1

pidof dwm >/dev/null && xdotool key super+F12
xwallpaper --output DP-4 --zoom "${XDG_DATA_HOME:-$HOME/.local/share}/bg" --output DP-0 --zoom "${XDG_DATA_HOME:-$HOME/.local/share}/bg2"
