#!/bin/bash

landscapedir=$WPDIR1
portraitdir=$WPDIR2

file1=$(ls ${landscapedir} | shuf -n 1)
file2=$(ls ${portraitdir} | shuf -n 1)

ln -sf ${landscapedir}${file1} ~/.local/share/bg && ln -sf ${portraitdir}${file2} ~/.local/share/bg2 && feh --bg-scale ~/.local/share/bg ~/.local/share/bg2
